### PR TITLE
Add initial arguments to SpringApplication.run

### PR DESCRIPTION
**Pull request by vsspt**
First of all, thank you very much for your project, it was very helpful.

I would like to request if it would be possible to include the arguments passed to SpringBootService.start(args), when starting the SpringBoot application.

Basically, on class SpringBootService, line 45, replace :

``` java
        SpringApplication.run(springBootApp);
```

with :

``` java
        SpringApplication.run(springBootApp, args);
```

### CODE REVIEW

**Comment by snicoll** [comment]
@kemitix wow looks like you've been quite busy on your fork there. Maybe we should find a single place for that stuff? 

@vsspt I apologize for the huge delay on this, for some reason I missed the notification of this pull request.

**Comment by kemitix** [comment]
@snicoll In my last job I had a need for this in production. Don't use this in my current job, but I'm happy to bring it up-to-date and get it into shape for wider availability.

@vsspt I wasn't aware of the pull request either.

**Comment by vsspt** [comment]
@kemitix, thank you very much for your reply.

Any idea when will you be able to release a new version with the change i requested implemented?

Best regards.

**Comment by snicoll** [comment]
@vsspt given the amount of changes here,  I am not sure this is the right place to discuss this. Most (if not all) changes are in @kemitix repo already.

**Pull request closed without merging**
